baseURL = 'https://patternlabs.xyz/'
languageCode = 'en-us'
title = 'Pattern Labs'

[params]
  description = "AI and Data Science explorations"
  keywords = "ai,machine-learning,data-science,programming"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Notebooks"
    url = "/notebooks/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
